<a href="https://colab.research.google.com/github/kancharlalavanya09/CSPT/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.

**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

**Import NumPy in Python**

In [1]:
import numpy as np

**NumPy Array Creation**

In [2]:
# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [3]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


**Create a 2-D NumPy Array**

In [4]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


**Create a 3-D NumPy Array**

In [5]:

# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [23]:

# create an array of integers
array1 = np.array([2, 4, 6])
#create an 2D array of integers
array2 = np.array([[1, 2, 3],
                [6, 7, 8]])
#create an 3D array of integers
array3 = np.array([[[1, 2, 3],
                [6, 7, 8]],

                [[1, 2, 3],
                [6, 7, 8]]])
 #check the data type of array1,array2
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
int64
int64


**Check dimensions of an Numpy Array**

In [36]:
array1 = np.array([2, 4, 6, 8])
print(array1.ndim)

1


In [25]:
array2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(array2.ndim)

2


In [28]:
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8]],

                [[1, 2, 3, 4],
                [5, 6, 7, 8]]])
print(array3.ndim)

3


**Check Size of Numpy array**

In [8]:
print(array1.size)

3


In [30]:
print(array2.size)

8


In [31]:
print(array3.size)

16


**NumPy Array shape Attribute**

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension.

In [37]:
array1 = np.array([2, 4, 6, 8])
print(array1.shape)

(4,)


In [9]:
array2 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array2.shape)

(2, 3)


In [32]:
array3 = np.array([[[1, 2, 3],
                [6, 7, 8]],

                [[1, 2, 3],
                [6, 7, 8]]])
print(array3.shape)

(2, 2, 3)


**NumPy Array itemsize Attribute**

In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [10]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4


In [39]:
array3 = np.array([[1, 2, 3],
                [6, 7, 8]])
print(array3.itemsize)

8


In [40]:
array4 = np.array([[[1, 2, 3],
                [6, 7, 8]],

                [[1, 2, 3],
                [6, 7, 8]]])
print(array4.itemsize)

8


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [12]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)



Data of array1 is:  <memory at 0x780609081fc0>
Data of array2 is:  <memory at 0x780608fa82b0>


In [42]:
array3 = np.array([[[1, 2, 3],
                [6, 7, 8]],

                [[1, 2, 3],
                [6, 7, 8]]])
print("Data of array3 is: ",array3.data)

Data of array3 is:  <memory at 0x7805f7838220>


**Access Array Elements Using Index**

In [13]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [44]:
array2 = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15]])

# access numpy elements using index
print(array2[0, 1])
print(array2[1,3])

3
15


In [45]:
array3 = np.array([[[1, 3, 5, 7],
                [9, 11, 13, 15]],

                [[10, 12, 14, 16],
                [18, 20, 22, 24]]])

# access numpy elements using index
print(array3[0, 1, 2])
print(array3[1, 0, 3])

13
16


**Modify Array Elements Using Index**

In [14]:
array1[1]=10
print(array1)


[ 1 10  5  7  9]


In [47]:
array2[1] = 20
print(array2)

[[ 1  3  5  7]
 [20 20 20 20]]


In [50]:
array3[1]= 30
print(array3)

[[[ 1  3  5  7]
  [ 9 11 13 15]]

 [[30 30 30 30]
  [30 30 30 30]]]


**2-D NumPy Array Indexing**

In [15]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)



4th Element at 2nd Row: 15
2nd Element at First Row: 3


**NumPy Statistical Functions**

Functions

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

In [16]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


In [52]:
array2 = np.array([[1, 2, 3, ],[2,4,6]])

# calculate the median
median = np.median(array2)

print(median)

2.5


In [53]:
array3 = np.array([[[1, 2, 3],
                [6, 7, 8]],

                [[1, 2, 3],
                [6, 7, 8]]])
median = np.median(array3)
print(median)


4.5


**Compute Mean Using NumPy**

In [17]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)


77.2


In [54]:
marks  = np.array([[76, 78, 81, 66, 85],
                   [76, 78, 81, 66, 85]])
mean_marks = np.mean(marks)
print(mean_marks)

77.2


In [57]:
marks = np.array([[23,25,26],
                 [2,6,7],

                  [3,8,9],
                 [12,14,16]])
mean_marks = np.mean(marks)
print(mean_marks)

12.583333333333334


**Standard Deviation of NumPy Array**

In [18]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)


6.368673331236263


In [61]:
marks = np.array([[6,4,2],[12,14,16]])
std_marks = np.std(marks)
print(std_marks)

5.259911279353167


In [59]:
marks = np.array([[23,25,26],
                 [2,6,7],

                  [3,8,9],
                 [12,14,16]])
std_marks = np.std(marks)
print(std_marks)

8.004772881780525


**Numpy Percentile**

In [19]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)


78.0


In [62]:
marks = np.array([[6,4,2],[12,14,16]])
std_marks = np.percentile(marks,50)
print(std_marks)

9.0


In [63]:
marks = np.array([[23,25,26],
                 [2,6,7],

                  [3,8,9],
                 [12,14,16]])
std_marks = np.percentile(marks,50)
print(std_marks)

10.5


**Numpy min**

In [20]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66


In [64]:
marks = np.array([[6,4,2],[12,14,16]])
std_marks = np.min(marks)
print(std_marks)

2


In [65]:
marks = np.array([[23,25,26],
                 [2,6,7],

                  [3,8,9],
                 [12,14,16]])
std_marks = np.min(marks)
print(std_marks)

2


**Numpy max**

In [21]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)

85


In [66]:
marks = np.array([[6,4,2],[12,14,16]])
std_marks = np.max(marks)
print(std_marks)

16


In [67]:
marks = np.array([[23,25,26],
                 [2,6,7],

                  [3,8,9],
                 [12,14,16]])
std_marks = np.max(marks)
print(std_marks)

26
